name: Update Skills in Profile README

on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * 1"   # Mondays @ 07:17 UTC
  push:
    paths:
      - .github/workflows/auto-skills.yml

jobs:
  update-skills:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build skills section
        uses: actions/github-script@v7
        with:
          script: |
            const username = process.env.GITHUB_REPOSITORY.split('/')[0]; // profile repo owner
            const perPage = 100;

            // 1) List public repos
            let page = 1, repos = [];
            while (true) {
              const { data } = await github.rest.repos.listForUser({
                username, per_page: perPage, page, sort: 'updated'
              });
              repos = repos.concat(data.filter(r => !r.fork));
              if (data.length < perPage) break;
              page++;
            }

            // 2) Sum languages across repos
            const totals = {};
            for (const r of repos) {
              const { data: langs } = await github.rest.repos.listLanguages({
                owner: r.owner.login, repo: r.name
              });
              for (const [lang, bytes] of Object.entries(langs || {})) {
                totals[lang] = (totals[lang] || 0) + bytes;
              }
            }

            // 3) Pick top languages (tweak as you like)
            const entries = Object.entries(totals).sort((a,b)=>b[1]-a[1]).slice(0, 12);

            // 4) Render shields badges (dark/light-friendly)
            const badges = entries.map(([lang]) => {
              const label = encodeURIComponent(lang);
              return `<img alt="${lang}" src="https://img.shields.io/badge/${label}-%23000000.svg?style=for-the-badge&logo=${label}&logoColor=white" />`;
            });

            const skillsBlock = badges.join('\n');

            // 5) Update README between markers
            const fs = require('fs');
            const path = 'README.md';
            let readme = fs.readFileSync(path, 'utf8');

            const stamp = new Date().toISOString().replace('T',' ').replace('Z',' UTC');
            readme = readme.replace(/<!-- SKILLS:START -->[\\s\\S]*<!-- SKILLS:END -->/m,
              `<!-- SKILLS:START -->\n<p>\n${skillsBlock}\n</p>\n<!-- SKILLS:END -->`);
            readme = readme.replace(/Last updated: [^<]*/m, `Last updated: ${stamp}`);

            fs.writeFileSync(path, readme, 'utf8');

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): refresh skills"
          file_pattern: README.md
